name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Build LiteX BIOS for QuickFeather
        run: make -f Makefile.quickfeather
